var celenueCatalog = [
    { id: 1, title: "Driftline Hoodie", price: "₱899.00", category: "Apparel", imgSrc: "Assets/products/DriftlineHoodie_apparel.png", desc: "Lightweight hoodie designed for casual wear." },
    { id: 2, title: "Noctra Mist", price: "₱289.00", category: "Fragrance", imgSrc: "Assets/products/NoctraMist_perfume.png", desc: "Soft floral scent with a warm musky finish." },
    { id: 3, title: "DermaLeaf Sunscreen", price: "₱229.00", category: "Skincare", imgSrc: "Assets/products/DermaLeafSunscreen_skincare.png", desc: "Non-greasy sunscreen for everyday protection." },
    { id: 4, title: "Velmora Skin Set", price: "₱699.00", category: "Kits", imgSrc: "Assets/products/VelmoraSkinSet_skincare.png", desc: "Daily skincare bundle for hydration and cleanse." },
    { id: 5, title: "Novan Polo Shirt", price: "₱279.00", category: "Apparel", imgSrc: "Assets/products/NovanPoloShirt_apparel.png", desc: "Smart-casual polo best for semi-formal looks." },
    { id: 6, title: "Lumera Glow Serum", price: "₱249.00", category: "Skincare", imgSrc: "Assets/products/LumeraGlowSerum_skincare.png", desc: "Light serum that helps brighten and smoothen skin." },
    { id: 7, title: "Velune Bloom", price: "₱269.99", category: "Fragrance", imgSrc: "Assets/products/VeluneBloom_perfume.png", desc: "Sweet floral scent with a gentle fruity touch." },
    { id: 8, title: "Gravix Groom Kit", price: "₱429.00", category: "Kits", imgSrc: "Assets/products/GravixGroomKit_groomingkit.png", desc: "Groom kit essentials for a neat and clean look." },
    { id: 9, title: "AetherWear Basic Tee", price: "₱199.00", category: "Apparel", imgSrc: "Assets/products/AetherWearBasicTee_apparel.png", desc: "Soft, breathable everyday shirt with a relaxed fit." },
    { id: 10, title: "Cindor Spice", price: "₱319.99", category: "Fragrance", imgSrc: "Assets/products/CindorSpice_perfume.png", desc: "Warm and slightly spicy fragrance for bold vibes." },
    { id: 11, title: "Trimor Precision Set", price: "₱299.00", category: "Kits", imgSrc: "Assets/products/TrimorPrecisionSet_groomingkit.png", desc: "Compact grooming tools for detailed trimming." },
    { id: 12, title: "Nuvia Night Cream", price: "₱289.00", category: "Skincare", imgSrc: "Assets/products/NuviaNightCream_skincare.png", desc: "Moisturizing cream designed for overnight skin recovery." },
    { id: 13, title: "Dravon Night", price: "₱329.99", category: "Fragrance", imgSrc: "Assets/products/DravonNight_perfume.png", desc: "Deep, rich fragrance made for evening use." },
    { id: 14, title: "Trivon Cargo Pants", price: "₱529.00", category: "Apparel", imgSrc: "Assets/products/TrivonCargoPants_apparel.png", desc: "Utility-style pants with multiple pockets for ample storage." },
    { id: 15, title: "Silks Lotion", price: "₱189.00", category: "Skincare", imgSrc: "Assets/products/SilksLotion_skincare.png", desc: "A smooth, lightweight lotion designed for everyday use." },
    { id: 16, title: "Lustra Veil", price: "₱289.99", category: "Fragrance", imgSrc: "Assets/products/LustraVeil_perfume.png", desc: "Elegant scent with soft powdery and floral notes." },
    { id: 17, title: "Solique Citrus", price: "₱750.00", category: "Fragrance", imgSrc: "Assets/products/SoliqueCitrus_perfume.png", desc: "Bright citrus blend for an energetic and fresh feel." },
    { id: 18, title: "Virex Street Shorts", price: "₱249.00", category: "Apparel", imgSrc: "Assets/products/VirexStreetShorts_apparel.png", desc: "Comfortable shorts made for movement and daily use." },
    { id: 19, title: "Barvex Beard Kit", price: "₱259.00", category: "Kits", imgSrc: "Assets/products/BarvexBeardKit_groomingkit.png", desc: "Complete beard care set for shaping and maintenance." },
    { id: 20, title: "Elrix Windbreaker", price: "₱499.00", category: "Apparel", imgSrc: "Assets/products/ElrixWindbreaker_apparel.png", desc: "Light protective jacket ideal for windy or slightly rainy days." },
    { id: 21, title: "Gentrix Care Kit", price: "₱379.00", category: "Kits", imgSrc: "Assets/products/GentrixCareKit_groomingkit.png", desc: "Daily hygiene kit for quick and easy grooming routines." },
    { id: 22, title: "Dermens Facial Cleanser", price: "₱249.00", category: "Skincare", imgSrc: "Assets/products/DermensFacialCleanser_skincare.png", desc: "Lightweight and gentle facial cleanser." },
    { id: 23, title: "Mirel Essence", price: "₱299.99", category: "Fragrance", imgSrc: "Assets/products/MirelEssence_perfume.png", desc: "Balanced scent combining floral and woody tones." },
    { id: 24, title: "Melone Summer Set", price: "₱699.00", category: "Apparel", imgSrc: "Assets/products/MeloneSummerSet_apparel.png", desc: "Comfortable matching top and bottom set." },
    { id: 25, title: "Beard Care Kit", price: "₱379.00", category: "Kits", imgSrc: "Assets/products/BeardCareKit_groomingkit.png", desc: "A set that helps keep facial hair clean, and well-shaped." },
    { id: 26, title: "Aerune Fresh", price: "₱399.99", category: "Fragrance", imgSrc: "Assets/products/AeruneFresh_perfume.png", desc: "Clean and airy fragrance perfect for everyday wear." },
    { id: 27, title: "Debrune Denim Pants", price: "₱499.00", category: "Apparel", imgSrc: "Assets/products/DebruneDenimPants_apparel.png", desc: "Durable denim jeans with a clean, modern cut." },
    { id: 28, title: "Klyro Active Tank", price: "₱179.00", category: "Apparel", imgSrc: "Assets/products/KlyroActiveTank_apparel.png", desc: "Sleeveless top built for workouts and active lifestyles." }
];